"""create document and document_chunks tables

Revision ID: d49aee469aba
Revises: 0afa4e016142
Create Date: 2026-01-20 16:05:22.724749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision = 'd49aee469aba'
down_revision = '0afa4e016142'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('provider_id', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('node_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id')
    )
    op.create_table('document_chunks',
    sa.Column('max_char_size', sa.Integer(), nullable=False),
    sa.Column('start_char_index', sa.Integer(), nullable=True),
    sa.Column('end_char_index', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('prev_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('node_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['prev_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_chunks')
    op.drop_table('documents')
    # ### end Alembic commands ###
