"""Update documents and chunks tables

Revision ID: b04270a1e99e
Revises: d49aee469aba
Create Date: 2026-01-27 04:15:12.217688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b04270a1e99e'
down_revision = 'd49aee469aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_prisma_migrations')
    op.add_column('document_chunks', sa.Column('document_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('document_chunks_source_id_fkey'), 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['id'])
    op.drop_column('document_chunks', 'start_char_index')
    op.drop_column('document_chunks', 'source_id')
    op.drop_column('document_chunks', 'max_char_size')
    op.drop_column('document_chunks', 'end_char_index')
    op.alter_column('messages', 'parts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('messages', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_unique_constraint('uq_prompt_version_number', 'prompt_versions', ['prompt_id', 'version_number'])
    op.alter_column('prompts', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Unique identifier for code usage (e.g. 'summary_agent')",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompts', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment="Unique identifier for code usage (e.g. 'summary_agent')",
               existing_nullable=False)
    op.drop_constraint('uq_prompt_version_number', 'prompt_versions', type_='unique')
    op.alter_column('messages', 'extra_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('messages', 'parts',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.add_column('document_chunks', sa.Column('end_char_index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('document_chunks', sa.Column('max_char_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('document_chunks', sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('document_chunks', sa.Column('start_char_index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_source_id_fkey'), 'document_chunks', 'documents', ['source_id'], ['id'])
    op.drop_column('document_chunks', 'document_id')
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    )
    # ### end Alembic commands ###
